### ISSUE TITLE
LDAP importer

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#10]
Implement functionality to import users from LDAP and to update account information.

**Comment by fubu** [comment]
I started a seperate library for the LDAP tasks: [fubu/nethz](https://github.com/fubu/nethz) (pull requests welcome :P).

The search feature is still quite basic (you have to provide a correctly LDAP-encoded search string), but will be super-awesome in the next iteration. Authenticating a user is also implemented.

To use it, add it to the requirements and do:

```python
from nethz import ldap

ldap_connector = ldap.AuthenticatedLdap("ADMIN_USERNAME", "ADMIN_PASSWORD")
ldap_connector.search("(cn=bconrad)")
ldap_connector.authenticate("bconrad", "connys_super_password")
```

Note: The connectors are designed to be used as application globals (define once when app starts up, use whenever a request comes in).

**Comment by NotSpecial** [comment]
Thanks to fubus library done in 65bb0007c2f2f0163aa4f5511944f7c44b2d1ac1
