### ISSUE TITLE
Authorization is untested

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#104]
Tests for authorization were removed in b60de97a06cabb043f48f19ae32061fa390622f2
See my comment on that commit. We need them back as I accidentally introduced a bug(#103) in 9b2113f7403cd548807b9a85289f0cd43aa7e6ac already, which was undetected due to those missing tests.

**Comment by NotSpecial** [comment]
Yes, it seems I have been overenthusiastic while removing the tests.

But since, as you noticed, there was some overlap with tests it might be useful anyway to take a look at how permissions are tested. 

Will fix soon(TM), I promise.

**Comment by Leonidaz0r** [comment]
Just for a quick overview here some things that need to be tested:

- Correct methods are allowed for all methods for root, admins, owners, registered and unregistered people (5 methods * 5 classes of users = 25 tests, I know this sucks, I wrote it twice)
- Check that indirect resolution of owner attribute works with POST and GET (This will test authorization.will_be_owner and utils.get_owner)

It might be a good idea to test utils.get_owner and authorization.will_be_owner directly and not use the API. POST and GET create a big mess around these functions and there might be different issues with the approaches. However then we also need a separate tests for GET result filtering (for example users should only see their own groups, groups moderated by them and groups with allow_self_enrollment set).

**Comment by NotSpecial** [comment]
I have decided to add the user tests and add an additional test for owners (see commit referenced above)

But the deletion of the groupusermember by the owner fails, although it should be allowed.

Furthermore the delete_permission filter is Equal to the get filter (which works fine)

So I cant really figure out where the Problem is coming from.

Any ideas?

**Comment by NotSpecial** [comment]
Found it. The etag was missing, which resulted in 403, but only the default error message was shown.

Will look into the error message thing - if this is only in testing or if a delete really returns just a generic 403 if the etag is missing

**Comment by NotSpecial** [comment]
Completed in e67fa1833cd91751882dded4d6a1b8307a6a6c78
