### ISSUE TITLE
Remove will_be_owner

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#106]
I have some Problems with the will_be_owner mechanic, I believe it adds complexity and confusion to the api and is not quite needed.

As far as I understand the function is used in the post permission filters in the following Way:

I want to join a group. A post to groupmemberships is only allowed for the owner, but since I will be owner I have permission to post.

In my opinion this is very confusing for several reasons:
A POST request only makes sense for a resource endpoint, not for an item endpoint.
Only a item can have an owner, so owner permissions only work for item methods and POST makes no sense here.
Furthermore by looking at the model / schema /docs you can not tell that you, as a user, are permitted to post.

I would rather add POST to the 'registered_methods' and validate the given fields properly:
* if not admin, only own id possible
* only public groups

Im my opinion, this would result in a much clearer request handling.
Am I missing something here which is the reason for the way it is done now?

**Comment by fubu** [comment]
Sorry for OT:

>  A POST request only makes sense for a resource endpoint, not for an item endpoint.

There are cases where a POST to an item endpoint makes sense: When you already know the ID under which you want to create that new item.

Can't comment on the real issue though. ;)

**Comment by NotSpecial** [comment]
While this makes sense, this is not what POST is intended for.

From http://tools.ietf.org/html/rfc7231#section-4.3.3:

"[Post is used for] Creating a new resource that has yet to be identified by the origin server"

If you want to place it at a certain ID, you have to use PUT

**Comment by NotSpecial** [comment]
Completed in e67fa1833cd91751882dded4d6a1b8307a6a6c78
