### ISSUE TITLE
Switching to Mongo

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#111]
Creating an issue for a topic that has been around for a while.

I propose switching the api from sql to mongo before going to production.

Main reasons:
- Eve-sqlalchemy is badly maintained, has security errors and lags behind eve substantially
- Eve is based on Mongo and with a document based database in mind, e.g. consider embedded documents. We are using this functions and our life would be easier with mongo.

Controversial points:
- Maintaining a mongo database
  *\* We could not uses ISG for easy database
  *\* But we should be capable of hosting the database
  *\* Alternative: Exernal hoster, although this might be expensive

Especially to make our api future proof we should get rid of eve-sqlalchemy. Implementing a competitive solution seems infeasible to me. So switching to mongo might be our best option.

Difficulties:
Several parts of our code use sqlalchemy functions, we have to rewrite that.
It is yet to be determined how much effort this would be.
In the "test_overhaul" branch I've already started to replace some functions to make our tests more database-agnostic.

We already talked about this quickly in chat. But I think collecting the arguments here is important for the future. So if I forgot anything, please add!

**Comment by hermannsblum** [comment]
Concerning the Maintenance of mongo vs. eve-sqlalchemy:

* As I see it, eve-sqlalchemy is causing us already a lot of work. 
* Given the case of a security vulnerability which makes it necessary to update eve, we can not be sure that sqlalchemy will work as they keep not up the pace and eve will not be tested against sqlalchemy.  
There will be a lot more documents helping future IT Teams maintaining a mongo database than fixing eve-sqlalchemy related bugs.

**Comment by fubu** [comment]
I'm not a big fan of Mongo (I really like relational databases), but I do see the problem with eve-sqlalchemy not being a first-class citizen of the Eve ecosystem. So instead of promoting a switch to a different, SQL-based REST framework ;) (NB there are now a few really good alternatives) I just want to highlight one thing I already mentioned in the chat back in time: Hosting externally is not just a monetary thing, it's also IMHO a bad choice because of data protection - we don't own our user's data, and I don't think we can (or should) just store them on a third-party server without their or the ETH's consent.

So I guess we should then run Mongo on our own server at ISG (maybe they can help us with a secure configuration or backups/snapshots) and force-subscribe the IT team to the Mongo security mailing list.

**Comment by NotSpecial** [comment]
This is settled too, **self hosted Mongo** seems the way to go.

This is a quite big overhaul which seems to be impossible to do in small steps because our sql-dependend code is not easilly abstracted and tested, e.g. see #116.

It doesnt really make sense to put a lot of effort into our sql testing database to to make it ready for the abstractions if we are going to get rid of it anyway.

We have been talking about an API only coding weekend to get this done - so lets get planning :D

**Comment by NotSpecial** [comment]
# How to switch to Mongo

Now that modularization is out of the way, we need to change the modules to use Mongo.

## General Problems

* SQLAlchemy statements
 Most diffiult to solve. In some situations there might be a drop in replacement using ``Eve``s data layer accessible with ``app.data``. Check out [the code](https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/mongo.py) to see what you can do. Otherwise we might just need pymongo methods (but I don't know much about them)

Some other statements like get_owners are more complicated. It might be possible to simplify the process here.

* Tests
Mostly because of the sqlalchemy statements.

## Module process

Right now, it looks more or less like this:

_endpoints.py_
```python
class Event(Base):
    (all the fields)

class EventSignup(Base(^)
def make_eventdomain():
    eventdomain = make_domain(Event)
    eventdomain.update(make_domain(EventSignup))

    (do updates)

    return eventdomain
```

*\__init__.py*
```python
from .endpoints import make_eventdomain

def init_app(app):
    register_domain(app, make_eventdomain())
```
How it should look later:

_endpoints.py_
```python
eventdomain = {
    'events:' {all the fields},
    'eventsignups': {all the fields}
}
```

*\__init__.py*
```python
from .endpoints import eventdomain

def init_app(app):
    register_domain(app, eventdomain())
```

So how to do this? Easiest way is just to do something like this in a python shell:
```python
>>>from amivapi import Events
>>>from pprint import pprint
>>>pprint(Events.make_eventdomain())
```

Copy the output and done! Now taking a look at [Eve](http://python-eve.org/features.html) and [Cerberus](http://docs.python-cerberus.org/en/stable/) to see if something can be improved.
(Because I don't think the auto generated schema used functions like "default" from Eve correctly)

**Comment by Tar-Tarus** [comment]
#133 ¯\_(ツ)_/¯
