### ISSUE TITLE
docstring style

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#112]
In the current status, most of our code is lacking proper docstrings and the existing ones are inconsistently formatted.

(Not blaming anyone here, my code is sadly part of this)

I think we need to agree on how to write our docstrings and update all of them.

There are a few popular options (which can also be parsed by the documentation processor sphinx)

If you scroll down a little in this [stackoverflow post](http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format) the user daouzli has written a very nice comparison.

I would vote for the google style docstrings since they offer the best compromise of readabilty and compactness imho.

From the [google python style guide](https://google.github.io/styleguide/pyguide.html#Comments)

``` python
def fetch_bigtable_rows(big_table, keys, other_silly_variable=None):
    """Fetches rows from a Bigtable.

    Retrieves rows pertaining to the given keys from the Table instance
    represented by big_table.  Silly things may happen if
    other_silly_variable is not None.

    Args:
        big_table: An open Bigtable Table instance.
        keys: A sequence of strings representing the key of each table row
            to fetch.
        other_silly_variable: Another optional variable, that has a much
            longer name than the other args, and which does nothing.

    Returns:
        A dict mapping keys to the corresponding table row data
        fetched. Each row is represented as a tuple of strings. For
        example:

        {'Serak': ('Rigel VII', 'Preparer'),
         'Zim': ('Irk', 'Invader'),
         'Lrrr': ('Omicron Persei 8', 'Emperor')}

        If a key from the keys argument is missing from the dictionary,
        then that row was not found in the table.

    Raises:
        IOError: An error occurred accessing the bigtable.Table object.
    """
```

What are your opinions?

**Comment by Leonidaz0r** [comment]
Good idea. I am fine with Google Syntax.

**Comment by hermannsblum** [comment]
I agree. Google Syntax looks good, it is much better understandable than reST. I would just add the version that is specifying the type. This is probably not a must-have, but certainly a nice-to-have.

    def add_value(self, value):
    """Add a new value.

       Args:
           value (str): the value to add.
    """
    pass

**Comment by fubu** [comment]
:+1: we're using the extended Google style (adding type information) at work for a long time now

**Comment by NotSpecial** [comment]
Thats settled then, we're going to use **google style with type info**!

Now on to actually updating everything ;)

**Comment by NotSpecial** [comment]
This is done mostly everywhere now :)
