### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#113]
We have a lot of unit tests, but there are not very well organized and have not top quality.

Main issues:
- In some places we test resources, in others functionality accross resources (e.g. test_deletions)
- Many test are very "copy pasty" which makes it hard to update them if anything changes
- They often have subpar documentation. It is hard to understand what exactly is being tested.
- They rely heavily on direct database access (see #111)

My proposal:
I think it is best to organize our tests by related endpoints, e.g. files_and_studydocs since this makes it easy to get an overview if the api reacts as expected when using it.
In my opinion we can never forget not just to check our function, but also if they are properly integrated into eve. Therefore we should always use GET, POST, etc. instead of accessing the database. This would also help to switch to mongo #111 

Please let me know how you would organize the tests or if you'd agree so we can decide on one style and start improving our unit testing.

**Comment by fubu** [comment]
I haven't looked at the current tests, but the last time I did I had a similar feeling.

The way we do tests at work is as follows:

* In general, every module `X` gets it's dedicated `test_X` file. In it, the basic functionality of such a *unit* is tested, at the lowest possible level. (If a function does not have many dependencies we usually directly write [doctests](https://docs.python.org/2/library/doctest.html), as they also serve as documentation how to use that function).
* For more complicated "request flows" over multiple API endpoints, we have separate *integration* tests, possibly in a different/separate folder or at least as seperate class in the "main" unit test file.

I think it makes sense to test the API as thorough as possible. That includes a lot of boring, boilerplate-kinda tests for simple GETs etc, but they are equally important (as the more complicated integration tests rely on working sub-modules - they should rather test edge cases than the default behaviours cross-endpoint).

As the API is heavily organized by resources/resource groups, I support your first proposal of grouping tests by "feature". *Discoverability* is a feature of clean codebases after all.

However when it comes to "preparing"/setting up a test I'm a strong proponent of "adding stuff directly to the database". First of all, "integration into Eve" should be covered by their own simple unit test for the respective resource: Tests should be small, concise, and focused. Secondly the tests should be as fast as possible: Using an in-process "real" web app to add data is the slowest form of them all. Instead we should abstract away adding resources to the database in the spirit of the `new_Y` methods we already have. These methods should take care that a unit test can set up a correctly working and *minimal* data set with little effort (and a few method calls). Never ever should we need to directly query the DB in the setup of a unit test.  FWIW it may be possible to re-use some functionality of Eve itself (it for sure has methods to get documents by id from the database for example). With a good abstraction switching to Mongo would be a non-issue.

As for the "subpar documentation", at work we use a combination of self-explaining test names, a simple docstring describing what the test is testing, and sometimes some comments throughout the test to help the reader what part is currently being tested. Quick example:

```
class FacebookLogin(util.WebTest):

    def test_reconnect_with_other_facebook_user(self):
        """Connecting an already connected user account to a different facebook account should fail."""
        setup_code_goes_here()

        # Connect user to facebook account A
        make_necessary_api_calls()

        # Connect user to a different facebook account B
        with self.assertRaises(ApiError):
            try_to_connect_user_b()
```

NB: You could say that using comments to structure your code is already a sign of a too complicated test, and comments quickly get outdated (= maintenance burden), but I still like to use them in tests specifically.

To conclude: An important feature of a good test suite are lots of small test cases which are as self-contained and focused as possible (test one thing, and test it well). The test suite should be extensive, and having twice as many LOC in tests compared to the actual application is not necessarily bad.

**Comment by NotSpecial** [comment]
The new tests are much better. Still some way to go, but I think I can close this.
