### ISSUE TITLE
Problem with cascading delete in test database

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#116]
There is something wrong with our test database and I have no idea what.

Situation:
Create group, user and groupmember or any other related resources.
Delete group/user.
groupmember Item should get deleted.

Now here's the thing: If the items were added to the db directly (via self.app.db. ...) it works.
If the items are added with self.api.post it doesn't.

I have created a test in the test_overhaul branch.
For more details take a look at d2d9102

**Comment by Leonidaz0r** [comment]
The switch to mongo solved this.
