### ISSUE TITLE
500 Internal Server Error when sending POST without any data to /groups

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#122]
This might affect more resources

**Comment by NotSpecial** [comment]
Which content type header are you using?

Any idea so far where the api crashes?

**Comment by NotSpecial** [comment]
Ok, quick testing shows this only seems to happen if no Content-Type is specified.

**Comment by NotSpecial** [comment]
This might be fixed in Eve 0.6:

> Fix: reinforce Content-Type Header handling to avoid possible crash when it is missing (Sebastien Estienne).

From the [changelog](http://python-eve.org/changelog.html).

Not completely sure, but it seems to match our problem.

**Comment by Tar-Tarus** [comment]
The current version of Eve is now officially 0.6.5 and thus this bug should be fixed.  ۜ\(סּںסּَ` )/ۜ
