### ISSUE TITLE
Post to sessions with existing username and wrong password crashes server

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#128]
Just discovered this while writing a little tool using auth over api.

Reproducing is easy, just send a post to sessions with your username and a random password, you'll get back a "internal server error"

I'm currently updating the auth to work with mongo anyway, but I wanted to create this issue to make sure I don't forget to include a fix to this ;)

**Comment by Tar-Tarus** [comment]
Well good thing we have moved to mongo and the issue is resolved. (◔/‿\◔)
