### ISSUE TITLE
Optional group membership expiry

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#132]
Currently groupmembers are part of the group forever.

Since groups are tied to permissions it would make sense to let them expire.
Currently the group moderators have to clean their members manually.

We are afraid that this will get forgotten easily and we will have lots of zombie group members.

But not all groups have permissions and need auto-expiry.

Therefore I would propose the following:

Add an optional _maximum_membership_duration_ field to groups with a default value of a year or something.
Setting it to None would disable the feature.

Then we would need a cron job that cleans up groupmemberships every night.

**Comment by marcoep** [comment]
The _maximum_membership_duration_ is not sufficient though, we need some mechanism to track the subscription time of each groupmember. I further propose a signupdate field (or so) in groupmembers.

**Comment by NotSpecial** [comment]
Thats right! But fortunately Eve takes care of that. *_updated* timestamps are saved automatically

**Comment by NotSpecial** [comment]
We now have this on groupmemberships, which is nice.

I am wondering if a default value (as a field for the `group`) would be useful.

E.g. adding a expiry of 6 months to the group vorstand so you don't have to add this for every new vorstand manually.

What do you think? Could this be useful?

**Comment by Leonidaz0r** [comment]
Membership expiration was added in f18ab9b945d07711854c8c08d818647d620dbebf. Do we need a default or can we close this now? Default may be very different for different groups.

**Comment by NotSpecial** [comment]
I am not talking about a default value for this field, but rather a default that can be set for a group.

E.g. The group vorstand would contain: "default expiration: 6 months" and the group kontakt "default expiration: 1 year"

So if I would add a member to the vorstand group without proving an expiration date it would be set to 6 months and for the kontakt group it would be set to 1 year.

I am not sure if this is useful, but just to explain my idea.

**Comment by Leonidaz0r** [comment]
Let's make a seperate issue for that, as that is not blocking version 1.0.
