### ISSUE TITLE
Make group name unique and additional lookup (Alex knows what he means...)

### ISSUE THREAD

**Issue by Tar-Tarus** [amiv-eth/amivapi#138]
Groups names currently do not have a 'unique' property in their schematas. If a tool is going to check for the clearance for a user, it will do so by querying the groups it belongs to. If the name of the group is not unique, then it might be just as easy to create a second random group named 'vorstand' and include oneself in it. When the GET Request then arrives to the API, then there is no way to differentiate between the two groups(real and fake) and a user will be cleared for a level he does not belong to.

**Comment by NotSpecial** [comment]
It was unique already. Adding the lookup now
