### ISSUE TITLE
Rename files in order to be conform to a certain source code organization.

### ISSUE THREAD

**Issue by Tar-Tarus** [amiv-eth/amivapi#139]
Currently, if one is looking for the schemata for the various resources, he will find them under files of different names. I suggest we settle for a standard name for the file containing the schema of the resource instead of having __"endpoints.py"__ for the events resource and __"model.py"__ for the groups resource.

**Comment by NotSpecial** [comment]
True that!

I would favour `model.py` consistently, since that iss basically where we define our data model for the resource,

**Comment by Tar-Tarus** [comment]
I'll change the names in that case and push it to the branch before we merge.

**Comment by NotSpecial** [comment]
Sounds good

**Comment by Tar-Tarus** [comment]
I also notice that we have different nomenclatures for files containing the authorization class...
Is that intended?

**Comment by NotSpecial** [comment]
Do you have an example?

**Comment by Tar-Tarus** [comment]
hmm I think it was with /users where the Auth class was in a file called __security.py__ and in others it was either in __init.py__ or in __authorization.py__.

**Comment by NotSpecial** [comment]
In users I called it security because it contains more that just the auth. 

I'll have a look at the other files.

**Comment by NotSpecial** [comment]
All enpoints.py are renamed to model.py

**Comment by NotSpecial** [comment]
I think we can close this issue. Objections?

**Comment by Leonidaz0r** [comment]
Agreed. If anyone thinks there is still a problem, another issue can be opened.
