### ISSUE TITLE
Switch to Eve-Swagger

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#140]
Eve-Docs seems to be dead. It might be useful to look at [Eve-Swagger](https://github.com/nicolaiarocci/eve-swagger) instead.

In any case we need to update the description fields. Probably if we switch to Eve-Swagger they need a completely different format.

**Comment by hermannsblum** [comment]
will be resolved with #145

**Comment by Leonidaz0r** [comment]
not finished yet

**Comment by hermannsblum** [comment]
Done in #145
