### ISSUE TITLE
The problem of News and Evets priority for display

### ISSUE THREAD

**Issue by Tar-Tarus** [amiv-eth/amivapi#144]

**Comment by hermannsblum** [comment]
I thought about this.

A simple solution would be to use the `_updated` or `_created` timestamps.
In addition, one could think about a "sticky" flag?

**Comment by Leonidaz0r** [comment]
Fields priority, time_advertising_start and time_advertising_end are added in cf87b64b02f29e4a1c4999dea3a0df6044015217.

You can now get a list of current events, ordered by priority and how long they have been on display like this (insert current time):

GET /events?where={"time_advertising_start": {"$lte": "2016-12-10T17:56:00Z"}, "time_advertising_end": {"$gte": "2016-12-10T17:56:00Z"}, {"show_infoscreen": true}}&sort=-priority,time_advertising_start

**Comment by Leonidaz0r** [comment]
Finished.
