### ISSUE TITLE
JSON schema vs Cerberus schema

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#158]
Currently we use cerberus schemas for event's additional_fields. There was a discussion, whether we should switch to JSON schemas, as those are more widely known outside the python community.

Thoughts?

**Comment by hermannsblum** [comment]
As there is a [jsonschema validation for python](https://pypi.python.org/pypi/jsonschema), but no cerberus schema validation for js, that would make client-side validation easier

**Comment by NotSpecial** [comment]
Aren't there some javascript libraries around to create jsonschema? And to create forms form jsonschema?

In my opinion something like this would be the main argument, because if something like this exists we would make life for the frontend team much easier.

**Comment by hermannsblum** [comment]
Most of the translation to json schema is done in #145 .
However, the `additional_fields` Are still cerberus. This should be done with a PR to our version of eve-swagger
