### ISSUE TITLE
README outdated and incomplete

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#166]
Our README is outdated: it still tells people to clone from the mongo-branch
and incomplete: it is missing any information about how to set up tests (which requires an additonal mongo-db with a hardcoded name + user)

Before fixing this, I think especially the second part could also be done more user-friendly (we already create a testing-db automatically for travis, why not for developers?).

**Comment by NotSpecial** [comment]
README has improved :)
