### ISSUE TITLE
Errors in online documentation

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#168]
I just noticed this while browsing our new [online docs](http://amiv-api.ethz.ch/docs#tag/User%2Fpaths%2F~1users%2Fpost)

If you follow the link you can see that for POST, the "_id" field is part of the parameters provided.
This is incorrect, since for POST requests the server determines the id and not the client. More practically, the api would reject this.

Does anyone have an idea why this happens? A problem in Eve-Swagger, maybe?

**Comment by NotSpecial** [comment]
I changed the headline since I noticed another error:

The documentation tells us to expect the status code "200" after a succesful POST, while it is "201" in reality.

**Comment by NotSpecial** [comment]
I believe the 200 is a error in [Eve-Swagger](https://github.com/pyeve/eve-swagger/blob/d63f6d18a5060b6b521719a79ec9d884d8e43a6f/eve_swagger/paths.py#L112)
I will address this there.

**Comment by Leonidaz0r** [comment]
More problems:
* GET displays things it should not display. For /sessions the GET part shows username and password, which are only for POST.
* Relations to other resources seem to hide the description. For example the moderator of a group has a description, but it is not shown.

**Comment by hermannsblum** [comment]
I remember having fixed all these bugs during the last coding-weekend^^ Are you sure you are using my fork of eve-swagger?

The relation-description thing is interesting...
