### ISSUE TITLE
Newsletter subscription

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#178]
Every user should be able to manage the newsletter subscriptions (Announce, LIMES, Bastli, etc.).

The list of subscribed users should be exported to a textfile (one email per line).
This file should be served by a webserver with password protection. This way, it is possible to synchonize the subscribed users with the Sympa mailing list server.

**Comment by NotSpecial** [comment]
This is already implemented for announce (every user can set his newsletter flag)

Do you have thought about how different newsletters should be handled? In particular, which other newsletters do we want? Should this be dynamic? Tied to api groups? What such newsletters currently exists, apart from the announce? Is there even a need for management of newsletters other than the announce?

**Comment by temparus** [comment]
At the moment, there exist four newsletters which are using the same sympa mailing list server.
I thought that it would be convenient for the users to handle the newsletter subscriptions related to AMIV at one single place.
As I see this could only be achieved with great effort. This feature is not really needed.
I will close this issue as it is already implemented for the announce newsletter.
