### ISSUE TITLE
Rename zoidberg_share

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#182]
We should rename the term zoidberg_share to cloud_share or something similar.
Zoidberg is the name of a server. It would be better not to tie options of the API to a server name.

**Comment by NotSpecial** [comment]
Yeah, that makes sense.

Maybe something like `requires_storage`?

**Comment by Leonidaz0r** [comment]
While the argumentation is right, is there a reason we have to do it? As far as I know the option is used by the amivcloud service developed last year, so changing it would require changing multiple tools.

**Comment by temparus** [comment]
You are totally right. The amivcloudapp uses this option.
Before going to production with the amivcloud, the amivcloudapp needs to be adapted to the newest nextcloud version anyways. So this would not be a problem.
