### ISSUE TITLE
API returns 502 when accessing certain eventsignups with users embedded

### ISSUE THREAD

**Issue by marcoep** [amiv-eth/amivapi#208]
Steps to Reproduce
-------------------------

1. login as user noah, get token
1. do an authenticated GET request to the following URL:
`https://amiv-api.ethz.ch/eventsignups?where={"event":"59e5fc1fedcb11000ae5ecd9"}&embedded={"user":1}&page=5`
a 502 should appear
1. If you change &page to 4 or 6, the API replies correctly.

Expected Behavior
------------------------
Return the eventsignups number 101 to 125 for the Noahs Wurstparty event.

pls fix
-------

**Comment by NotSpecial** [comment]
Cannot reproduce anymore with the current version of the api.

Feel free to re-open the issue if the problem should resurface again.
