### ISSUE TITLE
API does not allow filtering within embeddings

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#210]
The eve documentation claims to be able to do queries like `GET /groupmemberships?where={"group.name"="admin"}`. However, amivapi only returns an empty list.

*Steps to reproduce*
`curl -g  'https://amiv-api.ethz.ch/groupmemberships?where={%22$and%22:[{%22group.name%22:%22admin%22},{%22user%22:%2259e5f715edcb11000ae5ecd4%22}]}&embedded={%22group%22:1}' -H 'Authorization: 4XxU0WnjyVEiIZgMlwr9egSLmOXvnCMfJz-c2iO1ACk'`

**Comment by NotSpecial** [comment]
Are we on the latest version of Eve?

**Comment by NotSpecial** [comment]
I did some research, and I do not think this is supported by eve, nor will be soon.

As mongo does not have any native data-relations, filtering on related resources can not be implemented.

[Statement from Nicola on the matter](https://groups.google.com/forum/#!msg/python-eve/O4e1GTS3jZs/HSZxcK85BAAJ)
