### ISSUE TITLE
Add Cache-Control header to API response

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#214]
It happend a couple of times that the browser served the API request from the browser cache when reloading the page, which is absolute nosense.

To avoid this, the following header should be added to every response:
```
Cache-Control: no-store, must-revalidate
```

**Comment by temparus** [comment]
This can easily be done by adding the following line to the file `config.yaml`
```
CACHE_CONTROL: no-store, must-revalidate
```

I close this issue as it is a matter of configuration.

**Comment by NotSpecial** [comment]
Maybe it would make sense to add this to the default configuration?

I haven't looked into caching a lot -- would there be any downsides?

**Comment by temparus** [comment]
There are no direct downsides. For example the event list is requested only once on a website visit.

We do not really have data that can be cached for a longer period.

And more important is the fact that for PATCH and DELETE requests an etag is required, which is served with the GET request. If this request is server from cache, this value might be outdated and it is impossible to successfully send those other requests.
