### ISSUE TITLE
Add field authentication_method to user entity

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#215]
We should add an additional required field `authentication_method` with the values `"ldap"` and `"password"` to the entity user.

For transparency purpose, the documentation should be changed as follows:
The value of `password` is only used when `authentication_method` is set to `password`.

**Comment by NotSpecial** [comment]
Why is this required?

If a password is set, the api tries to use it for authentication. Otherwise it uses LDAP.

What do we get from adding this field?

**Comment by hermannsblum** [comment]
As from the chat: The basic problem is that there needs to be a "change your password" option for those users that do not authenticate with LDAP and you need to know which users should be displayed this option and which not.

**Comment by NotSpecial** [comment]
Ok, so the main issue is that a frontend does not know whether a user has a password set or not?

In this case I see why we would need this and I would go with the original proposal, since as you said it's the cleanest interface.

**Comment by NotSpecial** [comment]
On the other hand: when using an additional field, the frontend still can only tell if the user *wants* to use a password -- it can't tell if the user already has set one.

Maybe we need to provide feedback some other way. E.g. using a boolean field that is true if a password is set and false if not? This could be done easily in a hook, I think.

**Comment by NotSpecial** [comment]
Other idea: the hook currently removing the password field could maybe only remove the password field for other users? And for the users own password, it could replace it with some '*******' or similar.

This way other users don't get any info about how you are authenticating and you can tell if you have set a password (use pw auth) or not (use LDAP)

**Comment by temparus** [comment]
I think that your last idea would be the easiest one to implement and the most intuitive one too.

@Leonidaz0r @hermannsblum What do you think about that?

**Comment by hermannsblum** [comment]
As already mentioned, I basically also see these two options.

However, setting the return value of the password field to some defined arbitrary value is really the least intuitive way, as it is really not standard REST that a field should have very different contents for different methods (in GET the `password` field now shows whether or not the user has set a password, in PATCH and POST it however should never be set, except for when the user wants to set the password to the defined value). This can easily lead to confusion in client implementations and may result in accidentially setting a password (e.g. by GETting an opject, doing some manipulations on it and PATCHing it again). The better option in my opinion is therefore really to hide the password field alltogether and add the additional boolean field. I think the form as described in the original issue description would be the best understandable.

**Comment by cburchert** [comment]
If anything I would use a different field. Exactly for the reasons Hermann said. One important reason we wanted the API in the first place is that we have an interface easy to learn and where it is harder to do things wrong.

I think additional boolean fields generally don't add complexity. Seeing a boolean returned which is readonly is straightforward. Specific behavior of fields is not.

**Comment by cburchert** [comment]
Done in the pull request. There is now the projected field `password_set`.
