### ISSUE TITLE
Changing the Password

### ISSUE THREAD

**Issue by Moschn** [amiv-eth/amivapi#235]
Changing the password should also require the current password. Currently an attacker could steal a session token and then change the password and thus hijack the account.

**Comment by cburchert** [comment]
Maybe an easy way to implement this would be to require a session of a very
small maximum age to change the password (say 1 minute).

2018-02-10 17:02 GMT+01:00 Moritz Schneider <notifications@github.com>:

**Comment by temparus** [comment]
I like the approach of @cburchert. Other opinions? @NotSpecial @hermannsblum

**Comment by temparus** [comment]
This issue has been resolved with PR #260.
