### ISSUE TITLE
Export announce subscriber list

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#242]
The announce subscriber list needs to be accessible from the mailing list server over HTTP protected with basic authentication. 

There are two possible solutions:

1. Transfer the list to a samba share (or sshfs mount) running a web server on a regular basis.
2. Add another endpoint to the API serving the list of announce subscribers. This endpoint needs to be protected using HTTP basic authentication.

Opinions? @cburchert @NotSpecial @hermannsblum

**Comment by NotSpecial** [comment]
Adding an http endpoint with basic auth is easy in flask, I think this would be the solution to go to.

Do you have any details on the response format? What is expected by the mailing list server?

**Comment by temparus** [comment]
The response should be just plain text with the following format:

```
john.smith@sample.edu  John Smith
sarah.hanrahan@sample.edu  Sarah Hanrahan
```

**Comment by hermannsblum** [comment]
What is the difference between the group mailing lists and the announce mailing list? Why do we need 2 different. channels to export this data?

**Comment by temparus** [comment]
There are two completely different systems behind those two. The announce mailing list is required by the mailing list server, the group mailing lists are just forward files stored on the mail server.
