### ISSUE TITLE
Require legi number to be unique

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#251]
Currently, the legi number of a user does not get checked for uniqueness.
This should be done as this number is number is unique nationwide.

**Comment by NotSpecial** [comment]
The legi number is already unique (see these lines in [users/model.py](https://github.com/amiv-eth/amivapi/blob/master/amivapi/users/model.py#L71-L77)).

**Comment by NotSpecial** [comment]
Could you describe your issue in more detail? What problem did occur exactly?

**Comment by temparus** [comment]
Oh, that's true. I thought about a problem occurred after importing a database dump. As there are no constraints within MongoDB, this is not a problem with the API.
