### ISSUE TITLE
Remove invalid email addresses

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#265]
Whenever a student leaves the ETH, their email address gets invalid. We should somehow remove the email address from our database as it has no value anymore (and produces a lot of bounces for sending the announce).

Maybe we should the user just unsubscribe from the newsletter or delete the email address.

**Comment by NotSpecial** [comment]
How can we tell if a student has left ETH? Any ideas?

**Comment by temparus** [comment]
We could verify if the email address is still working using `SMTP.verify(email)` from `smtplib` [1].

[1] https://docs.python.org/3/library/smtplib.html#smtplib.SMTP.verify

**Comment by NotSpecial** [comment]
This does not seem quite pressing. If this should become a real problem, feel free to re-open this issue.
