### ISSUE TITLE
Permissions for groups can not be revoked w/o complete reset

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#267]
Original permission of a given group
```
"permissions": {
        "users": "readwrite",
        "sessions": "readwrite",
        "events": "readwrite",
        "eventsignups": "readwrite"
}
```

The PATCH request to change a group's permissions with 
```
"permissions": {
        "users": "readwrite",
        "sessions": "read",
        "studydocuments": "readwrite"
}
```

results in 
```
"permissions": {
        "users": "readwrite",
        "sessions": "read",
        "events": "readwrite",
        "eventsignups": "readwrite",
        "studydocuments": "readwrite"
}
```

In order to revoke any permissions completely for a given group, first we have to patch the `permissions` field with `null` before we can patch the resource with the desired permissions.

**Comment by hermannsblum** [comment]
As we found out, this is the [intended behaviour ](https://github.com/pyeve/eve/issues/712)in eve

A possible solution would be to change the type for `permissions` from `dict` to `list`

**Comment by NotSpecial** [comment]
I think the behavior of eve is really weird in this case, it's so inconsistent. Maybe we should submit a pull request to allow disabling this behavior in the config.

**Comment by NotSpecial** [comment]
I have created a pull request, lets see what the response will be!

https://github.com/pyeve/eve/pull/1140

**Comment by NotSpecial** [comment]
My pull request has been accepted. In the next release of Eve (0.8), we'll be able to disable this behavior in Eve.

**Comment by cburchert** [comment]
Eve 0.8 was released, that did not take long :)
