### ISSUE TITLE
Add "spotlight" resource

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#269]
# Situation

From time to time, different things need to be put into a spotlight, both API-internal and external things.

Examples:
- During the anniversary, a link to the anniversary homepage
- Link to the pvk tool when pvk signup is on
- Link to a event in the API, e.g. the GV

This spotlight is mainly relevant for the Website, but e.g. a AMIV Telegram bot could display them as well.

Mainly the AMIV board, in particular the "Info Vorstand" should control what is currently announced.

# Current Possibilities

I think this need is not very well covered by our current resources. The closest approach would be to create an event with high priority, but this is not ideal for several reasons:
- Everyone who can create an event can flag attempt to put it into the spotlight like this, which is not what we want, since it could create a situation where everything is marked for the spotlight (like everything is made sticky in the current website)
- To put external links in the spotlight, e.g. a link to the PVK Tool, we would need a "fluff" event that just points at the real target

# Proposal

Therefore, I would propose a new resource `/spotlights`, which allows to put either an API resource or an external resource in the spotlight, and is intently separate from the event resource.

A spotlight would require the following fields:
- title (de/en)
- subtitle (optional, de/en)
- image (optional? not sure if this is needed)
- internal link (resource + item id) *or* external link (url) 

What are your thoughts on this?

**Comment by hermannsblum** [comment]
As you say, this is a very hard to define usecase. I am also uncertain whether this really belongs to the API or whether it is a feature that belongs solely to the website? I really don't see any other usecase than a highlighted website position.   
When it comes to postings in social media or telegram, we need a lot more information than just the spotlight to abstract the variety of "promotion-strategies" and I don't think that should go into the API as also these things change too quickly.

**Comment by NotSpecial** [comment]
I am not sure if there is a usecase anymore, as the website is now online and nobody seems to miss this feature. Leaving it open until I get a chance to discuss it with someone from the website to resolve this.

**Comment by NotSpecial** [comment]
Ping @temparus

**Comment by NotSpecial** [comment]
With the current website, there does not really seem to be a need for this feature. Closing it for now.
