### ISSUE TITLE
State possible http urls in docs

### ISSUE THREAD

**Issue by roger-barton** [amiv-eth/amivapi#277]
To know what can be done with the api, an overview list of all possible urls for the api and what they can be used for would be really helpful. For example:

>/events - use to see events list, create events
/eventsignups - use to see list of event signups
...

This is a basic thing and shouldn't be hard or take long to do.

**Comment by NotSpecial** [comment]
This actually exists, head over to `api.amiv.ethz.ch/docs` and you'll get an overview for all resources, their accepted values etc.

If any information is missing there, don't hesitate to open a specific issue.

**Comment by roger-barton** [comment]
Great! Didn't know this website existed. Why isn't it advertised better in the readme(?!)

**Comment by NotSpecial** [comment]
We don't really want to make the code (in this case the Readme) depend on where the API is deployed, thats why we have put the link into the github description, here:

![image](https://user-images.githubusercontent.com/7079143/40931371-2754cbd6-682b-11e8-8a57-40712878192d.png)

But I see your point, maybe we should make it more prominent.

**Comment by roger-barton** [comment]
Haha, I actually did not see that, thanks!
