### ISSUE TITLE
API provided redirect side for OAuth

### ISSUE THREAD

**Issue by roger-barton** [amiv-eth/amivapi#278]
For app development during the OAuth process, a redirect site does not exist. So it would be good for the api to provide a secure website where the token etc is redirected to.
The app can then extract the token and other data from the url in the browser.

Or is there another way this should be done?

**Comment by NotSpecial** [comment]
For the development API deployment (api-dev.amiv.ethz.ch) we have registered `localhost` as a redirect for the Oauth ID `Local Tool` to test OAuth locally.

If you have any questions, just send me a message!

**Comment by temparus** [comment]
You should not use OAuth within the Android App. You can just make a POST to `/sessions` to get a token. OAuth does work only for websites.

**Comment by roger-barton** [comment]
@NotSpecial  I have already implemented it using `localhost` as the redirect on my local api instance, which is working very well. But this isn't meant for production use as it isn't secure, so I was hoping for a better solution. 
@temparus Using OAuth would be preferable as it would give more consistency and single-sign-on can be used for ease of use.

**Comment by NotSpecial** [comment]
Are we talking about the check-in Android app? Doesn't the app use a pin anyway?

In any case, since this is not really an API issue and more related to a specific tool, we should maybe continue this discussion in chat -- I think we could find an ideal solution quicker that way.

Is there a group chat for the checkin tool already? If yes, could someone invite me, please? :)

**Comment by temparus** [comment]
Well, the redirect URL does not have to exist. All the needed information is stored within the URL. It does not matter if the page can be loaded or not. The only thing is that it has to be registered as an OAuth client. To make sure that no one can misuse it, we should register the domain being used.

**Comment by roger-barton** [comment]
No its for a generic amiv app which I've started 'drafting'.

**Comment by roger-barton** [comment]
Agreed but it needs to be secure with https or something.
