### ISSUE TITLE
Does cascade delete work properly?

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#279]
steps to reproduce:

1. log in via OAuth as any user and select "remember me", so that a session token will be stored in the browser
2. delete your user using the OAuth session
3. Try to log in another time using OAuth
4. The API returns an internal server error

**Comment by hermannsblum** [comment]
Apparently, something is wrong with either the deletion of the session or the authentication against a deleted session.

**Comment by NotSpecial** [comment]
I can't recreate this issue, neither with tests, a local API nor with the dev api.

I will remove the labels and milestone for now.
@hermannsblum , can you maybe check if you still get the problem with the current version?

If so, can you give me the exact requests that cause the issue?

**Comment by NotSpecial** [comment]
We encountered the issue again with eventsignups, and I have found that they seem to [not have cascading delete configured](https://github.com/amiv-eth/amivapi/blob/master/amivapi/events/model.py#L219-L222)

I only tested he issue with groupmemberships, where it is properly configured.
