### ISSUE TITLE
LDAP Illegal action

### ISSUE THREAD

**Issue by tinogfroerer** [amiv-eth/amivapi#283]
Extraordinary members must not be allowed to switch their password back to LDAP.

**Comment by NotSpecial** [comment]
I think implementing this affects to little users to be work the time invested.

In general, extraordinary members might actually have a working LDAP login, e.g. extraordinary members from other fields of study. They must be allowed to continue using their LDAP login.

Thus we cannot just disable LDAP for extraordinary members and would rather use some detection mechanism, which would require some time to implement and test.

As we have few extraordinary members, and even fewer of them that would attempt to use non-existing LDAP logins, I do not think we'll be able to spare the time.

I'll close this issue. Should any serious problems arise from this, feel free to re-open it with additional details.
