### ISSUE TITLE
Documentation missing for endpoint GET /sessions/<token>

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#291]
**Observed Behavior**

`GET /sessions/<some-session-token>` returns the session corresponding to the given token.

`DELETE /sessions/<some-session-token>` is not allowed
(List returned by method `OPTIONS` does not contain `DELETE`.)

The behavior of the API is inconsistent.

**Expected Behavior**
Both `GET` and `DELETE` should work given the session token as ID.

**Comment by temparus** [comment]
The endpoint supporting tokens is actually very useful.

However, when such an inconsistent feature is implemented, it should be properly documented. As I can see, there does not exist any documentation for that.

I will change the title of the issue accordingly.

**Comment by NotSpecial** [comment]
Resolved in the new online docs.
