### ISSUE TITLE
Anonymous eventsignups (email only) should not contain the email of a known user.

### ISSUE THREAD

**Issue by marcoep** [amiv-eth/amivapi#330]
Pretty much as the title says.

Currently, its possible to have an eventsignup with a registered user with email x@y.ch AND at the same time a email-only eventsignup with the email x@y.ch.

This should not be allowed as AMIV members should be forced to use their useraccount for eventsignups instead of the anonymous signup functionality.

Any thoughts and ideas w.r.t. this?

**Comment by NotSpecial** [comment]
This makes sense and is not that hard to fix. I've submitted a PR to solve the issue.
