### ISSUE TITLE
No media data returned

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#337]
The API does not return any image data for some images which were accepted with a PATCH. The incident happened with the development instance.

The following errors were logged:

https://sentry.amiv.ethz.ch/share/issue/7ea7c36cb99a43ad9a59b0167f891b75/
https://sentry.amiv.ethz.ch/share/issue/f25e331b5f9e469086f20eb00d0729a5/
https://sentry.amiv.ethz.ch/share/issue/3a89a668c6584de5bba9e9afa744c70c/

**Comment by NotSpecial** [comment]
It's seems to be a ugly combination of cerberus trying to deep copy and file buffers from uploading a file.

First of all, why does cerberus deepcoopy at all?!

But anyway, I'll try to discover how the buffer gets into the error object, because that shouldn't be.
