### ISSUE TITLE
API crashes if format for sort parameter is wrong

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#340]
When the format for the sort parameters is incorrect, the API crashes and returns the status code 500.

It should return status code 400 (Bad request) instead.

https://sentry.amiv.ethz.ch/share/issue/8afe4c3c23a747e99691e5ab8a153ec0/

**Comment by NotSpecial** [comment]
This seems to be a problem with eve, and I have created [an issue in the eve repo](https://github.com/pyeve/eve/issues/1248).

Putting this issue on hold for the meantime.

**Comment by NotSpecial** [comment]
The issue has been fixed in eve, and as of #387 this is part of the API.
