### ISSUE TITLE
Announce Short text

### ISSUE THREAD

**Issue by lujobi** [amiv-eth/amivapi#351]
As discussed: One should be able to add a special text for the announce, such that not the whole text from the website will be sent
 
Issue for admintool: https://gitlab.ethz.ch/amiv/amiv-admintool/issues/94

**Comment by NotSpecial** [comment]
I am not sure whether I like this idea, it just created more data-fields with basically the same purpose. There's no nead to write novels in the event description, so there are usually not that long anyways.

Maybe you could provide more details on the discussion you are referencing?

**Comment by hermannsblum** [comment]
I agree with @NotSpecial here, wouldn‘t it just be an option to crop the text if it is too long in the announce and add a link like „read more“? this would be a standard technique.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lujobi** [comment]
Your solution @hermannsblum sounds like a nice solution, my fear was that either the announce would get way too long or the space for the website would have to be constrained by quite a lot.

**Comment by NotSpecial** [comment]
Great, let's try this first, then!

I'm going to close this issue. Feel free to re-open it with additional detail in case @hermannsblum 's suggestion should not work out.
