### ISSUE TITLE
Fair First-Come-First-Serve

### ISSUE THREAD

**Issue by lujobi** [amiv-eth/amivapi#352]
As discussed: Fair First-Come-First-Serve would be great.

**Comment by NotSpecial** [comment]
Which discussion are you referring to, can you provide more detail?

Fair-FCFS can be tackled in many different ways, are there any preferences and/or requirements?

**Comment by lujobi** [comment]
Sure, as almost always when talking about Fair-FCFS the Skiweekend comes up. Since now we have the one-click-login it depends even more on the internet connection than before. 
My idea for the Fair FCFS would be, that everyone who enrolls within the first minute will land in a pot from which the spots and place on the waiting list are drawn randomly.

**Comment by NotSpecial** [comment]
Thanks for your feedback.

How should the time delay be determined? Do you think an API-wide fixed value (easy) would be sufficient? Or do different events require different delays?

**Comment by lujobi** [comment]
I think one (fixed) minute should work out fine. It should mainly accommodate the different (decent) internet connections.

**Comment by NotSpecial** [comment]
Thanks for the feedback! That should be possible.

**Comment by temparus** [comment]
This is a duplicate of #110.
