### ISSUE TITLE
Moderator for Events

### ISSUE THREAD

**Issue by lujobi** [amiv-eth/amivapi#353]
As discussed lately with @temparus: moderators for a single event would be great, such that not only the vorstand-groupcan edit an event.

**Comment by NotSpecial** [comment]
Hi, could you please provide some more details on the usecase?

Would the following alternative be suitable as well?

- Create a group `Event Moderators` for "trusted" event team members and give this group permission to edit events.

- Add the relevant users, which are now able to moderate events, without relying on the vorstand.

Would this be enough? Or are individual moderation rights completely necessary?

**Comment by lujobi** [comment]
Hi, our idea was to be able to assign a certain event to a certain user (-group)  such that for example the OK can only edit their event. 
A group of trusted Event-Moderators probably will work out for most of the time, as long as those rights aren't given out unmindfully.

**Comment by hermannsblum** [comment]
The administrative overhead of keeping track of who should be able to edit events is kind of high. I think the moderator option would be quite intuitive and fit the existing organisational model

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NotSpecial** [comment]
Thank you for your feedback, @lujobi , good to hear that using a moderator group can work for you.

In this case I'll close this issue. Should using a group of event moderators raise any problems in the future, please feel free to re-open this issue with additional detail.
