### ISSUE TITLE
Event Validation does not Throw Error

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#355]
Steps to reproduce: 

Create an event with `catchphrase_de`, `time_advertising_start` and `time_advertising_end`. The API creates the event and sends 201 without any validation errors.

e.g. the following event was just created on the dev api: https://api-dev.amiv.ethz.ch/events/5c76eefbaa9d350001a3285b

**Comment by temparus** [comment]
What validation errors would you expect?

According to the documentation, only the fields `time_advertising_start` and `time_advertising_end` are required.

**Comment by NotSpecial** [comment]
The devil is in the details, the issue is about the `catchphrase_de` -- it should not be possible to set a catchphrase without a title as well.

**Comment by NotSpecial** [comment]
Closed by #376.
