### ISSUE TITLE
Unsubscribe from event always possible

### ISSUE THREAD

**Issue by I98** [amiv-eth/amivapi#360]
Apparently, people can unsubscribe from events even after the registration deadline.

**Comment by NotSpecial** [comment]
@I98 , could it be that the person attempting to unsubscribe was an admin, e.g. Vorstand?

If you are allowed to manage eventsignups, you can unsubscribe even after the deadline.

**Comment by I98** [comment]
Ok, that explains why i could unsubscribe myself.

**Comment by NotSpecial** [comment]
Phew, all good then :)
