### ISSUE TITLE
Remove resource beverages

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#383]
The resource `beverages` is not being used in production anyways as it is handled by another tool.

Therefore we should remove this resource from the API.

**Comment by NotSpecial** [comment]
Really? Thanks for the heads up. Is the other tool final, or is there any chance that this tool wants to use the API resource in the future?

**Comment by temparus** [comment]
The other tool is pretty final.

Actually we talked about that in February, when we switched to the new beerlog backend.
We ended up in our discussion that it does not make sense to have log entries for AMIV members in the API and a complete list of consumed beverages in the beerlog database. Other student associations do not send the user's identification but just the RFID number.

**Comment by NotSpecial** [comment]
Okay. Makes sense,  I wasn't a big fan of it being in the API anyways. So the resource is not used and we can simply remove it without consequences?

**Comment by temparus** [comment]
Yes, we can :)
