### ISSUE TITLE
Add separate Cache-Control header for media endpoint

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#389]
Media files are currently not cached. It would make sense to allow caching of those files as they take some time to load whenever one navigates on the AMIV website and they do not change that often.

I think that it would be reasonable to allow caching for one hour just for the `/media` endpoint.

**Comment by NotSpecial** [comment]
Update: Caching is now live and works :)

![image](https://user-images.githubusercontent.com/7079143/58768799-d9644700-85a0-11e9-8e15-2fe6a24b1e2b.png)

# Before

![image](https://user-images.githubusercontent.com/7079143/58768825-0f093000-85a1-11e9-90cc-e3fc2a1d2eb1.png)


# After

![image](https://user-images.githubusercontent.com/7079143/58768814-f6991580-85a0-11e9-887e-8c4ee2b0ad4c.png)

Of course, this could still be tweaked a bit, e.g. set a certain time interval for which images must not even be validated (i.e. no request at all), but I think for now this is enough :)
