### ISSUE TITLE
Pagination info totals wrong in GET request to /groupmemberships with embedded groups

### ISSUE THREAD

**Issue by marcoep** [amiv-eth/amivapi#394]
As pagination is enabled for the AMIV API and you request multiple data items (e.g. /users or /groupmemberships), the API supplies the items under the _items key. As at maximum 25 items are returned, some pagination info is supplied under the _meta key. In the _meta key, the current page (page), the maximum number of items per page (max_results), and the total number of results for the request (total) are delivered.

Currently, when GETting the following request:
`api-dev.amiv.ethz.ch/groupmemberships?where={"user":"5bc130c27fbf9a0001a284a5"}&embedded={"group":1}`
The _items list has 2 objects in it, but the _meta->total value shows only a 1.
Not embedding the group results in the correct _meta->total value.

We noticed this error because it triggered some internal AMIV API response sanity checks within amiv-checkin. #youcanneverdoenougherrorchecking

**Comment by NotSpecial** [comment]
This is addressed in a recent Eve update (https://github.com/pyeve/eve/issues/1268)

I'm currently updating the version, it should be fixed afterwards.
