### ISSUE TITLE
Additional .forward files for amiv mailboxes

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#404]
The Groups resource it intended to manage the internal mailing lists which are handles by `.forward` files by the mail server.

Additionally, we have some mailboxes (<something>@amiv.ethz.ch) on the mail server of the Informatikdienste of ETH Zürich. Because the authoritative mail server for amiv.ethz.ch mail addresses is the ISG mail server (where we handle our `.forward` files), we are required to keep a forward file for every mailbox hosted on the ID mail server so that emails from external senders will reach those mailboxes.

There are two solutions for this:

* Create a group for every mailbox so that the required `.forward` file exists on the ISG mail server.
* Create another settings option containing a list of `.forward` files which should be ignored by the API.

**Comment by NotSpecial** [comment]
Do those special `.forward` files need some specific content?

Or would it make sense to handle them like any other `.forward` files for a group,
e.g. allowing to add users there.

**Comment by temparus** [comment]
No, there should be no user added to those `.forward` files.

The problem with that is, that every mail sent from an ETH mail address (ID mail server) will be directly delivered to the mailbox and does never pass the ISG mail server. Therefore only external mails will be forwarded to the additional users added to the `.forward` file.

**Comment by temparus** [comment]
It is time that we proceed with addressing this issue.

@NotSpecial which solution presented above would you prefer?

**Comment by NotSpecial** [comment]
How many of these other files are we talking about? A handful? Many?

**Comment by lujobi** [comment]
about 12 per semester

**Comment by NotSpecial** [comment]
12 per semester as in "12 additional mailboxes" per semester?

**Comment by lujobi** [comment]
It is one per vorstand. which will be kept at most for 5 years. Ending in about 100. 
>That would make keeping them in a blacklist in the config very tedious. 

Do you see another possibility?

**Comment by NotSpecial** [comment]
Okay, I think we need to take a step back here. What are these mailboxes? What are they used for? Why do they exist?

I'm currently at a loss to judge what would be the best option to address the issue of "special mailboxes", as I do not understand their usecase.

**Comment by lujobi** [comment]
> - What are these mailboxes?

VSETH provides a separate mailbox for every Vorstand used for the address e.g. `amiv-luzibier@student.ethz.ch`. including shared mailboxes which can be forwarded to the successor
> - What are they used for?

forwarding e.g. `luzibier@amiv...` to the mailboxes hosted by VSETH
> - Why do they exist?
> - Do we really need them?

If we don't want  `amiv-luzibier@student.ethz.ch` then yes. (as it is currently used like that)

**Comment by NotSpecial** [comment]
Okay, I see.

So the `.forward` files will be e.g. called `.forward+luzibier@amiv.ethz.ch`? And their content will be just `luzibier@ethz.ch` or something? Or are they in any way special?

Do the forward files need to created by the api? Or do we just need to avoid removing them?

**Comment by lujobi** [comment]
Nothing special. 

creating by the API would be great, but preventing from deleting would do the trick. Maybe we could "look" into the `.forward` file and prevent deleting via a regex. As all the AMIV-Vorstand-mailboxes have very similar content (`amiv-<nethz>@ethz.ch`).

**Comment by NotSpecial** [comment]
Ah, so the main purpose is to collect all emails sent to `luzibier@amiv.ethz.ch` and forward them to the ETH mailbox, which is used by the Vorstand? Do I understand that correctly?

**Comment by NotSpecial** [comment]
And just to be sure: The mails for the VSETH mailboxes are the only ones that create issues with the `.forward` files? There is nothing else?

**Comment by temparus** [comment]
You should not forget that we also have non-personalized shared mailboxes (i.e. info@amiv.ethz.ch). But those also have a special structure (`smb-[0-9]+-amiv@ethz.ch`).

Instead of having just a mail fordwarding, board members and ressort email addresses have a real mailbox on the ETH Exchange Mailserver. For all other mailinglists with @amiv.ethz.ch, we still require the Mailserver of ISG.EE, so the MX records still have to point to this server.
ETH internal mails to those special mailboxes will be delivered directly to the mailboxes without looking at the MX records as it already knows the target. The forward files are required so that mails from external mailservers are delivered correctly into the mailbox. This is the only issue we know so far.

**Comment by lujobi** [comment]
>Ah, so the main purpose is to collect all emails sent to luzibier@amiv.ethz.ch and forward them to the ETH mailbox, which is used by the Vorstand? Do I understand that correctly?

Exactly

>And just to be sure: The mails for the VSETH mailboxes are the only ones that create issues with the .forward files? There is nothing else?

Yes, personal alias are not allowed. Only other problem see above.

**Comment by NotSpecial** [comment]
@temparus, thanks for your input! Files with a special structure are safe. The api only ever writes (or removes) files that start with the configured prefix (in our case `.forward+`. So a file like `smb-[0-9]+-amiv@ethz.ch` will not be touched.

**Comment by NotSpecial** [comment]
As far as I can tell, or only problem is the [Mail Cleanup Part of the CLI](https://github.com/amiv-eth/amivapi/blob/master/amivapi/cli.py#L54-L58).

I guess it's not possible to give these files a different prefix, as they need to be called `.forward+...`? Or is it possible to use a different prefix and get the correct behaviour? (Then the issue would be solved already)

**Comment by temparus** [comment]
Well, the special structure we talk about is within the file. So those files also start with `.forward+...`.

**Comment by NotSpecial** [comment]
Oh, I see. That's annoying.

**Comment by NotSpecial** [comment]
Depending on the file system on the server, we could just mark them as immutable with `chattr +i file` -- then the API can't delete them.
(We still might need to patch the API CLI so that it does not crash when encountering an immutable file).

If that is not an option, can we e.g. add a comment to the top of the forward file, something like `#PROTECTED` or similar, which we can use to identify files that should not be deleted? Or will that confuse the mail server?

**Comment by temparus** [comment]
A comment at the start of the file will definitively work. We have a lot of comments in those files. It is great when the API cleans them out in the group mailing lists :D

The solution with the comment sounds easiest to me. We then could also write an additional description into the file so that a future Sysadmin knows why there is such a comment.

@lujobi we should create a small command line tool to easily manage those special forwarding files so that the files wont be deleted when one forgets one step.

**Comment by NotSpecial** [comment]
Okay, that sounds feasible. Game plan:
- Add a new settings to the API that defines the string to protect files.
- In the CLI, check whether a file starts with this string, before deleting it.

Notes:
- Group files will still be completely overwritten by the API. Comments added to them manually will not persist when the group is updated in any way.
- Maybe we need comments for groupmemberships? But that should be a different PR, I guess ^^

**Comment by NotSpecial** [comment]
One last question: what's the syntax for comments in these files?

**Comment by temparus** [comment]
Comments start with `#`.

**Comment by temparus** [comment]
@NotSpecial Would you mind implementing this?
We should have this feature by the end of the semester.

**Comment by NotSpecial** [comment]
I'm unfortunately very busy at the moment, but I'll do my best.

Do you have a more concrete deadline?

**Comment by temparus** [comment]
The deadline is end of June. That's the time when the server where the current tool is running is turned off.

But you may hold for a moment, because we are just checking an alternative offered by VSETH IT.

**Comment by NotSpecial** [comment]
Out of curiosity, can you tell me more about this alternative?

**Comment by temparus** [comment]
This issues got out of date. In the meantime, the complete mailing system has been migrated to VSETH and is managed there using the groups management.
