### ISSUE TITLE
Make LDAP Server configurable

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#424]
We should make the LDAP servers configurable so that we can remove bad servers from the list.

https://github.com/amiv-eth/amivapi/blob/427334aa745db40aac71b275a76c207a5e6e3a7d/amivapi/ldap.py#L63

**Comment by cburchert** [comment]
It is configurable by changing the nethz repository and pushing a new
version. Given that such a change probably happens less than once a year, I
think that is an appropriate way to configure it. This also solves the
problem in a central location for all potential users of the library, which
reduces work in figuring out which servers are correct.

Just an opinion, so feel free to ignore it and add a way to configure it
more dynamically.

**Comment by temparus** [comment]
Currently, we have an issue that an LDAP Server gives a bad response and there is no way to temporarily remove a specific LDAP Server.

This would be very useful right now as we do not want to change the nethz repository for this.

**Comment by temparus** [comment]
We could set it to `None` by default so that the configuration from the `nethz` is being used by default.

**Comment by cburchert** [comment]
Ah never mind my comment then. I wasn't aware of the reason for this issue.

Another solution might be to have an external load balancer that would handle unavailable replicas of the LDAP services, but I guess that doesn't currently exist and might also be overkill.

So I agree with your solution.

**Comment by temparus** [comment]
More investigation revealed that the reason for the problems was that our LDAP admin account was deleted by the sysadmins. Our solution from above does not make a difference then. We do not need to change the LDAP servers, so we might just keep the solution we have so far.
