### ISSUE TITLE
Event Sign Off Email

### ISSUE THREAD

**Issue by lexiea** [amiv-eth/amivapi#432]
It would be great if people received an email when they sign off from an event just like when they sign up.
Something like

Hello XY

We hereby inform you that your signup for XY was removed.

Best Regards,
AMIV

**Comment by NotSpecial** [comment]
Sound reasonable, and would be a good issue for someone new to tackle -- it does not require a lot of API knowledge to realize this.

The emails can be implemented similar to the signup mail [defined here](https://github.com/amiv-eth/amivapi/blob/master/amivapi/events/emails.py#L16-L37).

This email gets sent from the function that updates the signup queue ([reference](https://github.com/amiv-eth/amivapi/blob/c7aaecf5b680756bcaa5397a5774a48617839157/amivapi/events/queue.py#L55))


Similarly, we could just update the function that processes deleted signups to also send a mail ([this one](https://github.com/amiv-eth/amivapi/blob/c7aaecf5b680756bcaa5397a5774a48617839157/amivapi/events/queue.py#L89-L95))

TODOs would be:
- Implement a new mail function that sends the "you deleted your mail" (maybe with different versions whether you are on the waiting list, if that adds any value).
- Call that function from the function that processes the deleted signups.
- Write a test :D (check the existing tests for inspiration)

I will not have time for this in the near future, but happy to give advice to anyone who wants to give it a shot.

**Comment by NotSpecial** [comment]
And thanks for the feedback, @lexiea!

**Comment by kunerj** [comment]
Implemented and merged in #441 .
