### ISSUE TITLE
Blacklist: Add line on where people can pay to get off the Blacklist

### ISSUE THREAD

**Issue by d-portenier** [amiv-eth/amivapi#433]
Many blacklisted persons ask, how they can get off the blacklist.
==> Add a line to the sent email.

**Comment by NotSpecial** [comment]
Hi, thanks for your engagement.

The default text for the blacklist mails are defined [here](https://github.com/amiv-eth/amivapi/blob/master/amivapi/settings.py#L127-L149), feel free to submit a pull request with an updated text!

**Comment by kunerj** [comment]
Implemented with [PR 441](https://github.com/amiv-eth/amivapi/commit/eeef08a486785c5f4d9275f690a5a615808d654c#diff-a996c0c360c371a8a0d7d4dfd1cd8c0bc7d4d344d489c6aa726705636cee1e3bR10).
