### ISSUE TITLE
LDAP sync fails if user is not enrolled

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#436]
If a user with an n.ethz account is not enrolled, some fields in the LDAP response are missing.

The amivapi crashes with an error 500 and prevents those users from logging in.

**Comment by NotSpecial** [comment]
Can you provide some more details please, or even a particular `n.ethz` for which it fails?
Or even better, the (anonymized) LDAP response so I can see which fields are missing?

From the given information, it will be hard to reproduce the issue.

Thanks!

**Comment by temparus** [comment]
This issue was actually meant as a todo for the upcoming coding weekend.

We need to further investigate which fields are missing.
If you want to take care of this issue in the coming days, I can provide you the `n.ethz` by other means.

**Comment by NotSpecial** [comment]
Nope, coding weekend sounds great 😄 If it's incredibly critical you can reach out again, but my time is unfortunately quite limited lately. I'll be available to help with question as much as I can, though!
