### ISSUE TITLE
Don't use eval, it's evil!

### ISSUE THREAD

**Issue by fubu** [amiv-eth/amivapi#60]
`eval` is considered evil in a lot of languages, not just python. A few of the reasons why:

1. It can be insecure, as it allows to execute arbitrary code.
2. There is almost always a better way to do it.
3. It makes debugging difficult, and it is slow.

Currently, its only usage is in [validator.py](https://github.com/amiv-eth/amivapi/blob/master/amivapi/validation.py), and the way it is used at least does not immediately pose a risk for executing arbitrary code (you doged bullet 1 there). However, there is indeed a cleaner way to solve the problem at hand -- how about an explicit mapping of resource name to function reference instead:

```python
# before the first usage:
resources_with_extra_checks = {}

# when in need of the extra check:
def pre_replace_check(resource, document, original):
    fn = resources_with_extra_checks.get(resource)
    if fn is not None:
        fn(document)

# at the bottom of the file:
resources_with_extra_checks.update({
    # You could now name your function whatever you want to
    'forwardusers': check_forward_users,
    'events': check_events,
    # Heck, you could even get rid of these ugly double underscores!
    '_eventsignups': check__eventsignups,
})
```

If putting that at the bottom of the file bothers you, there are also solutions to this, for example a simple decorator (I'm sure you can come up with one yourselves :))

**Comment by Leonidaz0r** [comment]
It seems to be gone
