### ISSUE TITLE
Long Term: OpenID on top of API

### ISSUE THREAD

**Issue by fubu** [amiv-eth/amivapi#61]
Hey,
I was thinking a bit more about the whole API key thingy, and I was wondering if you could lay out some use cases why, in _your_ opinion, API keys would be needed?

**Comment by Leonidaz0r** [comment]
So... your idea?

**Comment by hermannsblum** [comment]
We also need an API key for the info-screen to access the signups of an event and show if any places are left. This can not be done outside of a session and you need special permissions for that.

**Comment by fubu** [comment]
> We also need an API key for the info-screen to access the signups of an event and show if any places are left.

In my opinion events should at least return the number of remaining open spots per default (number of spots minus accepted signups). I don't think getting this information should require more than the usual "event access" permissions.

**Comment by NotSpecial** [comment]
I agree. Related to #48 - discussion on signups should be continued there

**Comment by Leonidaz0r** [comment]
Any more ideas on this issue? The current situation is, that we have one API key for the coffee machine and one for the beer machine. The info screen has its information publically available now and other services use regular sessions.

**Comment by fubu** [comment]
My idea was to build an OpenID Connect service on top of the API, providing a Single-Sign-On (think the Google login page for AMIV services). Such a single-sign-on has the advantage that the user always only types in his password on one website, not for every tool AMIV might ever have.

Anyways, since OpenID Connect builds on top of OAuth 2.0, people would have to authorize the "beer"/"coffee" services for accessing their legi information, so that no API keys would be needed.

Unfortunately my calendar currently does not allow such a project. I'll come back to it when that changes :)

**Comment by NotSpecial** [comment]
Together with VSETH and ETH, a identity provider is being implemented using Keycloak. Implementing this on top of AMIV API will not be necessary.
