### ISSUE TITLE
Test authorization for bulk insert

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#63]
Test what happens with bulk inserts where some objects are not allowed. Document what happens.

**Comment by NotSpecial** [comment]
I think we need to extend this. As of now bulk inserts are allowed on most resources but almost never tested.

**Comment by NotSpecial** [comment]
This is not relevant anymore.

- The authorization doesn't care whether its a single or bulk insert, it simply checks resource write access (without looking at the payload, this is now exlusively done in validation which works per item anyway so works with single and bulk insert)

- There are no different hooks for single/bulk-insert anymore, so they all are implemented like we have bulk insert.
