### ISSUE TITLE
CamelCase vs _underscores

### ISSUE THREAD

**Issue by cburchert** [amiv-eth/amivapi#68]
In the User model we have "ldapAddress" however generally we seem to use underscores. My suggestion: Use underscores everywhere.

Opinions?

**Comment by Leonidaz0r** [comment]
I have changed the field's name to ldap_address in bcf08540182939dd6374297b91be4f3476a7aa7e

**Comment by fubu** [comment]
This is a tricky question: On one hand, the python default is using underscores (CamelCase is only used for classes). On the other hand, in JavaScript/JSON the default is camelCase -- and the model attributes are mapped 1:1 to JSON keys... Not sure what I prefer here.

**Comment by hermannsblum** [comment]
As discussed today: We want to present pure JSON, so for all resource fields we will use CamelCase

**Comment by NotSpecial** [comment]
We could implement a function that turns all underscore into camelCase after register_schema.

Pro:
* python model still defined in underscore

Con:
* schema file even more confusing

Opinions?

**Comment by NotSpecial** [comment]
I talked to Leonidazor about this, is actually a bad idea since eve /eve-sqlalchemy assumes that schema and model have the same name.

So changing by hand in the model seems to be the easiest way.

**Comment by Leonidaz0r** [comment]
Any further opinions here? I am not sure we should change too much anymore.

**Comment by fubu** [comment]
I think as long as eve/eve-sqlalchemy does not allow to easily convert between both styles we should stick to one for the field names, on both sides.

There is however something where IMHO camelCase would help legibility: endpoint names/urls. I personally prefer `/groupAddressMembers` over `/groupaddressmembers`. (That of course would require schema changes and is backward incompatible.)

**Comment by Leonidaz0r** [comment]
We wait vor migration to MongoDB and afterwards we can change this easily, so discussion postponed.

**Comment by Leonidaz0r** [comment]
Let's revisit this one. While we can change everything as we like now, people are already using the API. For that reason I would stick with the current names. If we do another revision of the API like the mongo switch this might be something to look at.

**Comment by fubu** [comment]
I'm okay with the underscores for attribute names for now - just keep it consistent everywhere. For that reason I still think we should apply the same logic to collection/resource names, and make them use underscores as word separator as well: `event_signups` etc. I also think if we agree to change that, now is still the best time to do so (easy fixes for the clients).

(For the record: Above I proposed camelCase for resource names, but that is probably a lot more error prone for developers than a real word separator.)

**Comment by NotSpecial** [comment]
The code uses a consistent style now: resource names are all lowercase, no underscores, atrributes use underscores.
