### ISSUE TITLE
Store GV and board meeting minutes in API

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#69]
Currently the meeting minutes of both the board meetings an GV are regularly uploaded to be AMIV website.

Should ne new API handle this as well?
Or should it be only part of the new website?

**Comment by Leonidaz0r** [comment]
We had stuff with only calendar entries in the google calender so far and we still wanted to use it anyway, just insert events created via API automatically.

**Comment by fubu** [comment]
I don't understand @Leonidaz0r answer, but the minutes are just ordinary files, aren't they? What exactly do you want the API to do here?

**Comment by NotSpecial** [comment]
I think the topic is not clear. Just for clarification: (meeting) minutes = Protokolle 

I was just wondering about storage. Should the minutes be stored and accessed by the api or should they be kept separate?

**Comment by fubu** [comment]
Ah, I was still under the impression that `Files` could store *any* files... but as I just realized, they are tied to `StudyDocuments`.

I think it makes sense to allow the API to also store files other than study documents, and I also think the abstraction we were discussing once (with the "bundles of files", of which `StudyDocuments` are just a special case with specific metadata) would allow for more general use cases. Adding extra resources every time a new kind of file/bundle needs to be implemented does not scale (and is probably also not really DRY).

**Comment by NotSpecial** [comment]
Discussion about this:

Meeting minutes for special groups should be stored in drive/dropbox/whatever_service_the_team_is_using to ensure only the right people can see this.
The zoidberg-shares (as soons as they are working) would be ideal for this.

For all registered users available should be GV and board minutes. Those should be stored in the API to ensure access only for registered users.

**Comment by temparus** [comment]
I think that we should to add the following API endpoints:

* board minutes (or general minutes connected to a group)
* general assemblies to store documents and possibly link an event

Opinions? @cburchert @NotSpecial @hermannsblum

**Comment by hermannsblum** [comment]
@temparus can you update us a bit, what makes zoidberg unable to share a document with all registered amiv members?

In a way, there is no technical difference between having a group folder for a commission and a group folder for all members. Therefore, I would like to avoid these rather narrow usecases and have something that works for all groups.

**Comment by temparus** [comment]
You are right that Nextcloud is more suitable to share files, but I don't understand what you mean by having something that works for all groups. GV documents are official documents which no other group needs to have.

The AMIV Cloud can share folders with the public out of the box. We can just configure a share link manually.
For the general assemblies, it is possible but more difficult as not everyone should have access to it. We can integrate that into our amivcloudapp for Nextcloud where we can share folders readonly.

**Comment by temparus** [comment]
As the AMIV Cloud is launched and all requirements for the discussed documents are fulfilled by Nextcloud.
