### ISSUE TITLE
Tool-related email confirmation

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#70]
For anonymous confirmation, the api should not send a link to a tool specified by hardcoding or config but dynamically chosen relating on the client the user used to sign up.
The client will send a link to the api (we will document the exact specifications the tool behind this link has to satisfy) and the api will use the link to this tool to send the email to the user.
Therefore, the API no longer depends on a specific signup tool.

**Comment by Leonidaz0r** [comment]
This was solved in the mongo branch with a simple redirect cf84f9b0db8e977ab4e684e0dab0d1c1345017f3
