### ISSUE TITLE
Remove unneccessary fields on User model

### ISSUE THREAD

**Issue by fubu** [amiv-eth/amivapi#72]
As discussed earlier, we should re-evaluate some fields on the User resource. This issue is about answering the general question "what is the use case to have this field in the API?". If there is none, we should remove it; adding it again later is simple and would not break the API.

* So, can you come up with use cases for the following fields (both pulled from LDAP)?
    * `birthday`
    * `ldap_address`
* Do you have other fields to challenge?

Another clarification from our previous discussion: The `phone` field should not be pulled from LDAP, but rather be an optional field to save one's phone number for internal organizational purposes (what we're currently doing in the wiki).

For the legi number, I opened a seperate issue: #73

**Comment by hermannsblum** [comment]
I think birthday can be more and more important as we had people at the freshman-weekend who were not 18
