### ISSUE TITLE
Evolve Forwards to Groups

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#74]
Reshape current resource "Forwards":

Rename to "Groups"
Add field for various email addresses

Idea: Groups can be used to map organisational structure of amiv

**Comment by Leonidaz0r** [comment]
More specific new layout:

Group:
- name

ForwardAddress:
- mail address
- relationship to group(a group can have different mail aliases)

GroupUserMember:
- relationship of user and group

GroupAddressMember:
- relationship to group
- email address

I have implemented this design and am modifying the tests to work with it.

**Comment by Leonidaz0r** [comment]
Done in 4306e29a281d08a4b449a56f3128b647e4e56478
