### ISSUE TITLE
Events: Additional flags for publishing on website, newsletter, etc

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#78]
For events, we need some options to request the following:

* Do I want my event to show up in
  * Email Newsletter
  * Website Newsfeed
  * Infoscreen
  * calendar
  * (facebook

We could implement this as a field 'flags' which is a list that supports only certain entries (you cannot create your own flag)

Clients could look for the "API approved" flags, e.g. the infoscreen tool only considers events where "infoscreen" is in "flags"

**Comment by Leonidaz0r** [comment]
Why would we want to implement this as an unspecific flags field? This are exactly 4(or 5) boolean fields. More fields dont hurt while random unstructured data may very well do so.

**Comment by NotSpecial** [comment]
I think I have not made myself clear. The flags field will not be unspecific. Lets call the field 'where_to_appear' or however.

This field contains now a list of certain keywords, in our example only
'calendar', 'announce', 'website', 'infoscreen' are available (cerberus can do that)

So it would look like this:
```
'where_to_appear': ['website', 'announce']
```

So first of all it is  **not** random unstructured data. I would go as far to say since all this fields have the same purpose, this version is actually more structured than just throwing random boolean fields into the resource

I think this is also more intuitive. If you want to know where you event will show up you dont have to check the description of every field if it means that your event will show up somewhere, you just have to look at one field and will get every place

And lastly I think it will be quite relevant to add fields here. I agree with you that it shouldn´t be possible to put whatever flag you want in there as I said above. There should be a list of available flags - but this list could be expanded more easily.

e.g. someone writes a tool that can post events to facebook automatically.
Now of course not every event should be posted to facebook so we want to extend the api to allow explicit choice of 'show in facebook'

Your proposal requires a new field with chance of the database. My proposal require a change in settings that will only affect the validator.

I think it is quite possible that we want to integrate new tools that way in the future.

To answer a question: It is not random and unstructured, its in my opinion a logical collection of fields with the same purpose

**Comment by NotSpecial** [comment]
Would you agree with me on that point? or could there be problems with collecting the flags in one item?

**Comment by Leonidaz0r** [comment]
As SQLAlchemy does not support lists of flags in any good way we just use one boolean field per flag.
Solved in 77786ed37ba0e64c47899c6de85ebe6872ca4b79
