### ISSUE TITLE
file testing not working in python 3

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#79]
The test _files_studydocs does not work in python 3, somthing in werkzeug is crashing.

It is to note that only the testing fails, running the server with python 3 and using requests library to send a file myself worked perfectly fine.

Could not find the reason why testing fails. According to most stackoverflow posts it should work in py34 when using BytesIO, but it still doesn't.

Also tried just using a real file instead of doing it in-memory with BytesIO - same result.

Any ideas?

**Comment by NotSpecial** [comment]
Removed python 3 from travis testing because of this.

Maybe as soon as we update eve (and with that flask and werkzeug) it might work properly again.
Until then py34 testing is suspended.

(tox.ini is still untouched, so running tox can be used to test py34 locally as well)

**Comment by Leonidaz0r** [comment]
Everything works in the mongo branch. Closing this, as irrelevant now.
