### ISSUE TITLE
API support for GV attendance-lists

### ISSUE THREAD

**Issue by marcoep** [amiv-eth/amivapi#82]
I recently got another idea to incorporate into the api:

How about a possibility to store/manage/readout lists of the attendants of a GV? Imho, GV attendance-lists are about equally important as VS-protocols which are also managed by the api.

The super-all-inclusive implementation of such a functionality could incorporate all functions of today's GV tool (and more, like checking if someone is checked-in twice). If we want it simpler, one could only implement storing of attendance-lists, where no later modification etc. is possible.

What do you guys think? If this is desired, I would take over the implementation hereof (or at least try it).

**Comment by Leonidaz0r** [comment]
The question I would like to ask here(and which has previously been asked, when we talked about this last time) is: Will there ever be more than one tool to access the attendance lists? The API is not designed to be used as a universal data backend for all AMIV Tools. The idea is to use it as the central information hub for everything shared by more than one application.

So any ideas for other tools than the one used during GV which would want to know who was there?

**Comment by marcoep** [comment]
Yeah, I guess you are right.

But Alex already saw a possibility to manage GV attendance through the already existing event management of the API. So no change in the API is required at all for a prospective new GV tool.
