### ISSUE TITLE
ASCII NULL character \0 problems with database?

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#84]
In dbce21e643950d57aa113b9e5d7fd03f1dc687a9 I changed a test to make travis.ci happy.

The Problem is: In the test configuration for some reason the \0 is ignored leading to identify user "user1" although it receives "user1\0"

I was not able to reproduce the issue on other systems so I changed it.
Tested on Windows and a quick Fedora install.

If anyone has an idea why travis would fail here please feel free to comment.
Since travis runs ubuntu the problem might lay there? If I have free time I will try this.

**Comment by Leonidaz0r** [comment]
This is not a security problem and should only affect people including zero characters in fields, which should not happen or is people's own fault. Won't fix.
