### ISSUE TITLE
Provide API Schema in jsonschema format

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#91]
The javascript acces library (handling most api request in the amiv web apps) should contain a input validator in the future. For this reason it would be nice if we could use an automatically generated schema.

the docs/json.spec endpoint already does this but returns our cerberus schema.

It would be nice if we could return it in the jsonschema standard because there are javascript solutions to use this directly for validation.
(Using the cerberus file we would have to parse it all ourselves)

I think it should not be to complicated to generate the jsonschema from our cerberusschema.

http://json-schema.org/

**Comment by hermannsblum** [comment]
To my knowledge the cerberus-schema actually is a json-schema. So the parsing should not be a problem.
Is it because of the special data-types?

**Comment by hermannsblum** [comment]
Fixed as swagger also uses jsonschema #145

**Comment by Leonidaz0r** [comment]
not fixed yet

**Comment by hermannsblum** [comment]
This is (now really merged) done in #145.
There is still the issue of `additional_fields`, see #158. However, I am not sure whether we want 2 issues open for the same problem. Can we close this?

**Comment by NotSpecial** [comment]
Done now! (Or in a second when travis finishes)
