### ISSUE TITLE
New property for groups: need a boolean field if group should have a share on Zoidberg / Brainslug.

### ISSUE THREAD

**Issue by marcoep** [amiv-eth/amivapi#95]
Groups need a boolean field if the group should have an own share in the AMIV file storage. Not every group need an own share: "dieueblichenverdaechtigen" for example dont need one. "vorstand" and "hopo-itet" do.

**Comment by Leonidaz0r** [comment]
done in e6f3267b550ac69e781f1b54eb1e21845fb411c3
