### ISSUE TITLE
Tidy up group self enrollment

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#98]
The following changes should be made:

1. Remove in bootstrap
     app.on_insert_groupaddressmembers += (authorization.group_public_check)

groupaddressmembers can only be created by moderators anyway

2. Move authorization.group_public_check into the validator _validate_self_enroll

**Comment by NotSpecial** [comment]
Done in e67fa1833cd91751882dded4d6a1b8307a6a6c78
