### ISSUE TITLE
Rename fields with same name but different meaning

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#99]
The fields Group.is_public and Event.is_public have the same name but mean two different things.

Event.is_public sets whether people without an AMIV Account can register themselves for that event using only an e-mail address using token confirmation.

Group.is_public states whether people having an AMIV Account can enroll themselve in that group. There is no confirmation here and not only an E-Mail address.

I propose the names Group.self_enroll_allowed and Event.address_only_signup_allowed

**Comment by fubu** [comment]
I propose to start such field names with a verb: `Group.allow_self_enrollment` and `Event.allow_email_signup`

Just remember that there are only two hard things in computer science:

1. Cache invalidation
2. Naming things
3. Off-by-one errors

**Comment by Leonidaz0r** [comment]
Implemented your suggestion
